### PR TITLE
Cpu middleware

### PR DESCRIPTION
**Pull request by davidzhangnyc**
WHAT DOES THIS PR DO?

Adds CPU metrics of each pod

HOW TO TEST THIS PR:

Ensure minikube is running with `minikube start`
Run `gh pr checkout 33 && npm install && npm run backend`
Send a GET request to localhost:3000/metrics and ensure you get a console log of an array of objects back with podId and cpu with no cpu values of 0 and podIds of undefined.

### CODE REVIEW

**Review by JefZheng — APPROVED** [review]
Will need to format output, convert to percentage, and move the code over to the electron backend controller in the next PR

**Comment by dlande000** [comment]
Screen Shot 2021-07-15 at 11 15 46 AM
 
this is the correct console.log, right?

**Comment by dlande000** [comment]
I had to remove a leading `/` on line 52 of the metricsController file to get this to work.

**Review by dlande000 — APPROVED** [review]
Approved, but as Jeff noted, we need to move this work over into our Electron server now.  (EDIT: I meant "now" like "now that this PR is done," not "now" like "DO IT NOW!")

**Review by Hydroelectric29 — APPROVED** [review]

**Pull request merged**
